---
title: "Correlation between morphological and molecular Rates"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
---



```{r setup, include=F}

library(ape)
library(phytools)
library(ontophylo)
library(dplyr)
library(parallel)
library(viridis)
library(ggplot2)
library(deeptime)
library(mgcv)
source("R/utils-ST.R")
source('R/region_class.R')
source('R/utils-edge-age.R')

knitr::opts_chunk$set(
  echo = TRUE,       # show code by default
  warning = FALSE,
  message = FALSE
)
```

## Read Trees

```{r}
tree <-readRDS("data/hym_tree.RDS")
tree_ml_mol <- read.tree("data/HYM-NUC-70%-SWSC.tre")

# READING IQTREE
# - nex tree  is derived from original iqtree by manually rerooting (Athalia)
# tree_ml_morph <- read.nexus("ml-morpho/iqtree/ml-morpho.nex")
tree_ml_morph <- read.tree("ml-morpho/iqtree/ml-morpho.treefile")
```

## Root tree_ml_morph

```{r}
node <- findMRCA(tree_ml_morph, c("Abia_lonicerae_USNMENT01322220", "Lophyrotoma_zonalis_USNMENT01339631"))
tree_ml_morph <- root(tree_ml_morph, node=node, resolve.root = T)
```


## Align tree_ml_morph
```{r}
library(bnpsd)
#plot(tree_ml_morph, show.tip.label = F)
tree_ml_morph <- ladderize(tree_ml_morph, right = TRUE)
tree_ml_morph <- tree_reorder(tree_ml_morph, tree$tip.label)
plot(tree_ml_morph, show.tip.label = F)
```

## Align tree_ml_mol

```{r}
to_prune <- setdiff(tree_ml_mol$tip.label, tree$tip.label)
#to_prune %>% length()
tree_mol <- drop.tip(tree_ml_mol, to_prune)
```

## Check if tips order is the same
```{r}
all(tree$tip.label==tree_mol$tip.label)
all(tree$tip.label==tree_ml_morph$tip.label)
```


## Plot edges to make sure they are aligned

```{r}
plot(tree, show.tip.label = F, use.edge.length=F)
edgelabels(cex=0.5)

plot(tree_mol, show.tip.label = F, use.edge.length=F)
edgelabels(cex=0.5)

plot(tree_ml_morph, show.tip.label = F, use.edge.length=F)
edgelabels(cex=0.5)
```


## Edge Ages

```{r}
edge_age_tbl <- edge_average_age_table(tree)
edgelabels(cex=0.5)
```


## Correlation

```{r}
# mor <- tree_ml_morph$edge.length
# mol <- tree_mol$edge.length

# filter out very small rates in morphology
df <- tibble(
  mor = tree_ml_morph$edge.length,
  mol = tree_mol$edge.length,
  age = edge_age_tbl$avg_edge_age
) %>%
  filter(mor >= 0.00001)


df <- df %>% mutate(across(everything(), log))
df
```

```{r}
cor_test <- cor.test(df$mor, df$mol, method = "pearson")
cor_test

cor_test2 <- cor.test(df$mor, df$age,  method = "pearson")
cor_test2

# model <- lm(log(mol) ~ log(mor) + log(age), data = df)
model <- lm(mor  ~ mol + age, data = df)
summary(model)
```

## Plot

```{r}
library(ggplot2)

ggplot(df, aes(x = mor %>% log, y = mol %>% log)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, linewidth = 1) +
  theme_minimal() +
  labs(
    x = "Morphological branch length",
    y = "Molecular branch length",
    title = "Morphological vs Molecular Branch Lengths"
  )
```

```{r}
library(ggpubr)


p <- ggscatter(
  df,
  x = "mor",
  y = "mol",
  add = "reg.line",
  conf.int = TRUE,

  add.params = list(
    color = "steelblue4",
    fill = "lightsteelblue",
    linewidth = 1.2
  ),

  xlab = "Log morphological branch length",
  ylab = "Log molecular branch length"

) +
  stat_cor(
    method = "pearson")


ggsave(
  "figures/morph_vs_mol.pdf",
  plot = p,
  width = 7.2,
  height = 3.5

)
```



```{r}
library(ggplot2)

p <- ggscatter(
  df,
  x = "mor",
  y = "age",
  add = "reg.line",
  conf.int = TRUE,

  add.params = list(
    color = "steelblue4",
    fill = "lightsteelblue",
    linewidth = 1.2
  ),

  xlab = "Log morphological branch length",
  ylab = "Log average branch age"

) +
  stat_cor(
    method = "pearson")

ggsave(
  "figures/morph_vs_age.pdf",
  plot = p,
  width = 7.2,
  height = 3.5

)
```
