---
title: "Make Rate thru Time using Branch-specific rates"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r setup, include=F}

library(ape)
library(phytools)
library(ontophylo)
library(dplyr)
library(parallel)
library(viridis)
library(ggplot2)
library(abind)
library(dplyr)
library(purrr)
source("R/utils-ST.R")
source('R/region_class.R')


knitr::opts_chunk$set(
  echo = TRUE,       # show code by default
  warning = FALSE,
  message = FALSE
)
```



## Read data

```{r}

# read replicates
tree <-readRDS("data/hym_tree.RDS")
rates.multi <- readRDS("data_out/br_rates_all.RDS")

class(rates.multi)
length(rates.multi)
dim(rates.multi$cranium)

```

## Reshape as list of 1000 tables 152 x 15

```{r}
# names of body regions
regions <- names(rates.multi)
n_reps  <- ncol(rates.multi[[1]])   # 1000
n_branches <- nrow(rates.multi[[1]]) # 152

# build new list: one element per replicate
replicate_list <- lapply(1:n_reps, function(j) {
  # extract column j from each body region and bind
  mat <- sapply(rates.multi, function(region_mat) region_mat[, j])
  # ensure it's a matrix with rows = branches, cols = body regions
  mat <- matrix(mat, nrow = n_branches, ncol = length(regions))
  colnames(mat) <- regions
  mat
})

# drop adult
replicate_list <- lapply(replicate_list, function(x) x[, -c(1:15), drop = FALSE])

# check dims
length(replicate_list)   # 1000
dim(replicate_list[[1]]) # 152 x 1
```




## Make rates

```{r}
rates_time <- branch_rate_thru_time_Multi(tree, replicate_list, n_points = 1000, time_points = NULL)
head(rates_time)

```


## Save

```{r}
saveRDS(rates_time, file='data_out/rates-thru-time-larva.RDS')
```



## Plot mean with empirical 95% confidence interval

```{r}
p <- ggplot() +
  geom_ribbon(data = rates_time, aes(x = time, ymin = lower, ymax = upper),
              fill = "blue", alpha = 0.2) +
  scale_x_reverse(breaks = seq(0, 280, by = 50)) +
  geom_line(data = rates_time, aes(x = time, y = mean),
            color = "black", size = .3) +
  theme_minimal()

p
ggsave("figures/metrics_thru_time/rate-thru-time-larva.pdf", p, width = 3.5*2, height = 1.6*2, dpi = 300, units = "in")
```





## Correlations

### Read data

```{r}
# Rates
rates_time <- readRDS('data_out/rates-thru-time-larva.RDS')

# Se
Se <- readRDS('data_out/s-per-replicate.RDS')


head(rates_time)
head(Se)

```

### Select unique rates for correlation

```{r}
rates_unique <- rates_time %>%
  arrange(time) %>%                                 # ensure time is increasing
  mutate(mean_prev = lag(mean)) %>%                 # compare with previous
  filter(is.na(mean_prev) | mean != mean_prev) %>%  # keep only when mean changes
  select(time, mean)  

time_uni <- rates_unique$time
#saveRDS(time_uni, file='data_out/unique_time_points.RDS')

nrow(rates_unique)
plot(rates_unique$time, rates_unique$mean)
```

### Select unique Se and Dispr

```{r}
se_uni <- Se %>%
  filter(time %in% time_uni)
head(se_uni)

```

### Rate vs. Se

```{r}
# x <- rates_unique$mean 
# se <- se_uni$mean_s

x <- (rates_unique$mean + 1e-7) %>% log
se <- (se_uni$mean_s + 1e-7) %>% log

```

#### Pval
```{r}
cor.test(x , se,  method = 'pearson')
```
#### Plot

```{r}
model <- lm(se ~ x)
summary(model)

plot(x, se)
# Fit linear model
abline(model, col = "red", lwd = 2)
```

#### Residuals

```{r}

x <- (rates_unique$mean + 1e-7) %>% log
se <- (se_uni$mean_s + 1e-7) %>% log
t <- rates_unique$time

m_x  <- lm(x  ~ t)
m_se <- lm(se ~ t)

res_x  <- resid(m_x)
res_se <- resid(m_se)

cor.test(res_x, res_se, method = "pearson")
```



### Rate vs. BAMM

```{r}

x <- (rates_unique$mean + 1e-7) %>% log

y <- function(z)  -0.00298507 * z + 0.06
ba <- y(rates_unique$time) 
plot(rates_unique$time, ba, xlim=c(280,0))
```

#### Pval
```{r}
cor.test(x , ba,  method = 'pearson')
```
#### Plot

```{r}
model <- lm(ba ~ x)
summary(model)

plot(x, ba)
# Fit linear model
abline(model, col = "red", lwd = 2)
```
#### Residuals

```{r}


t <- rates_unique$time

m_x  <- lm(x  ~ t)
m_ba <- lm(ba ~ t)

res_x  <- resid(m_x)
res_ba <- resid(m_ba)

cor.test(res_x, res_ba, method = "pearson")
```
