---
title: "Make Rate thru Time using Branch-specific rates"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
---


```{r setup, include=F}

library(ape)
library(phytools)
library(ontophylo)
library(dplyr)
library(parallel)
library(viridis)
library(ggplot2)
library(abind)
library(dplyr)
library(purrr)
library(deeptime)
source("R/utils-ST.R")
source('R/region_class.R')


knitr::opts_chunk$set(
  echo = TRUE,       # show code by default
  warning = FALSE,
  message = FALSE
)
```



## Read data

```{r}

# read replicates
tree <-readRDS("data/hym_tree.RDS")
rates.multi <- readRDS("data_out/br_rates_all.RDS")

class(rates.multi)
length(rates.multi)
dim(rates.multi$cranium)

```

## Reshape as list of 1000 tables 152 x 15

```{r}
# names of body regions
regions <- names(rates.multi)
n_reps  <- ncol(rates.multi[[1]])   # 1000
n_branches <- nrow(rates.multi[[1]]) # 152

# build new list: one element per replicate
replicate_list <- lapply(1:n_reps, function(j) {
  # extract column j from each body region and bind
  mat <- sapply(rates.multi, function(region_mat) region_mat[, j])
  # ensure it's a matrix with rows = branches, cols = body regions
  mat <- matrix(mat, nrow = n_branches, ncol = length(regions))
  colnames(mat) <- regions
  mat
})

# drop larva
replicate_list <- lapply(replicate_list, function(x) x[, -16, drop = FALSE])

# check dims
length(replicate_list)   # 1000
dim(replicate_list[[1]]) # 152 x 15
```




## Make rates

```{r}
rates_time <- branch_rate_thru_time_Multi(tree, replicate_list, n_points = 1000, time_points = NULL)
head(rates_time)

#plot(rates_time$time, rates_time$mean, type = 'l', xlim=c(280,0))
#plot(rates_time$time, rates_time$upper, type = 'l', xlim=c(280,0))
```

## Normalize to check sensitivity

#### Read

```{r}
# tot states per BR
load('data/char_num.RDA')
tot_states <- lapply(anat_ent_state, function(x) sum(get_len(x)) ) %>% unlist
tot_states

#rates_norm <- apply(rates, 1, function(x) x/tot_states) %>% t
# head(rates_norm)
# head(rates)
```


### Normilized Rates
```{r}
#apply(replicate_list[[1]], 1, function(x) x/tot_states) %>% t

replicate_list_norm <- lapply(replicate_list, function(x) {
  apply(x, 1, function(y) y/tot_states) %>% t
})

rates_time_norm <- branch_rate_thru_time_Multi(tree, replicate_list_norm , n_points = 1000, time_points = NULL)
```



## Save

```{r}
saveRDS(rates_time, file='data_out/rates-thru-time.RDS')
```



## Plot mean with empirical 95% confidence interval

```{r}
p <- ggplot() +
  geom_ribbon(data = rates_time, aes(x = time, ymin = lower, ymax = upper),
              fill = "blue", alpha = 0.2) +
  scale_x_reverse(breaks = seq(0, 280, by = 50)) +
  
  geom_line(data = rates_time, aes(x = time, y = mean),
            color = "black", size = .3) +
  
  coord_geo(
    dat = "periods",
    pos = "bottom",
    size = 2,
    expand = FALSE,
    height = unit(0.35, "cm"),
    lab = T
  ) +
  
  labs(
    x = "Time (Ma)",
    y = expression("Rate"~(Myr^{-1})),
    colour = NULL
  ) +
  #theme_minimal()
  theme_classic() +
  theme(
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  )
p
ggsave("figures/metrics_thru_time/marginal_rate.pdf", p, width = 3.5*2, height = 1.6*2, dpi = 300, units = "in")

```



## Plot median with empirical 95% confidence interval

```{r}
ggplot() +
  geom_ribbon(data = rates_time, aes(x = time, ymin = lower, ymax = upper),
              fill = "blue", alpha = 0.2) +
  scale_x_reverse(breaks = seq(0, 280, by = 50)) +
  geom_line(data = rates_time, aes(x = time, y = median),
            color = "black", size = .3) +
  theme_minimal()
```


## Plot mean rates Normalized

```{r}
p <- ggplot() +
  geom_ribbon(data = rates_time_norm, aes(x = time, ymin = lower, ymax = upper),
              fill = "blue", alpha = 0.2) +
  scale_x_reverse(breaks = seq(0, 280, by = 50)) +
  geom_line(data = rates_time_norm, aes(x = time, y = mean),
            color = "black", size = .3) +
  theme_minimal()

p

```
