---
title: "Branch-specific rates"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
---




```{r setup, include=F}

library(ape)
library(phytools)
library(ontophylo)
library(dplyr)
library(parallel)
library(viridis)
library(ggplot2)
library(abind)
library(dplyr)
library(purrr)
library(tidyr)
source("R/utils-ST.R")
source("R/utils-branch-ama.R")
source('R/region_class.R')


knitr::opts_chunk$set(
  echo = TRUE,       # show code by default
  warning = FALSE,
  message = FALSE
)
```



## Make branch-specific rates for adult phenome

```{r}
# Load data.
load("data_out/paramo_stm_adult_final.RDA")
load("data_out/paramo_amalg_adult.RDA")

########################
### ADULT CHARACTERS ###
########################

# Pre-allocate list to store branch rates for all partitions.
br_rates <- setNames(vector(mode = "list", length = length(anat_ent)), names(anat_ent))
br_rates_ind <- setNames(vector(mode = "list", length = length(anat_ent)), names(anat_ent))

i = 1
for(i in 1:length(anat_ent)) {

  # Get anatomical partition name.
  ana_name <- names(anat_ent)[[i]]

  # Get character IDs.
  char_IDs <- anat_ent[[i]]

  # Pre-allocate list to store rates.
  stm_list_rates <- setNames(vector(mode = "list", length = length(char_IDs)), char_IDs)

  # Loop over all individual characters.
  for (j in char_IDs) {

    # Import stochastic map.
    stm_list_rates[[j]] <- readRDS(paste0("stmaps/", j, ".RDS"))

  }

  # Summarizes amalgamated rates for all samples.
  stm_summ <- ama_branches_multi_char(stm_list_rates)

  # Re-organize data as matrix.
  br_rates_mat <- do.call(cbind, stm_summ)
  rownames(br_rates_mat) <- paste0("BR_", 1:dim(br_rates_mat)[1])
  colnames(br_rates_mat) <- paste0("S_", 1:dim(br_rates_mat)[2])

  # Summarizes amalgamated rates across all samples.
  stm_summ_mean <- summarize_branch_rates_multi(stm_list_rates, "mean")
  stm_summ_mean <- setNames(stm_summ_mean, paste0("BR_", 1:dim(br_rates_mat)[1]))

  # Store branch rates for all characters of an individual partition.
  br_rates[[i]] <- br_rates_mat
  br_rates_ind[[i]] <- stm_summ_mean

}

# Save R object.
#saveRDS(br_rates, file = "data_out/br_rates_adult.RDS")
#saveRDS(br_rates_ind, file = "data_out/br_rates_adult_ind.RDS")
```

## Make branch-specific rates for larval characters

```{r}
#########################
### LARVAL CHARACTERS ###
#########################

# Set character IDs manually.
char_IDs_lv <- c("CH3", "CH4", "CH5", "CH9", "CH10", "CH6_CH7_CH8")

# Pre-allocate list to store rates.
stm_list_rates_lv <- setNames(vector(mode = "list", length = length(char_IDs_lv)), char_IDs_lv)

# Loop over all individual characters.
for (j in char_IDs_lv) {

  # Import stochastic map.
  stm_list_rates_lv[[j]] <- readRDS(paste0("stmaps/larval/", j, ".RDS"))

}

# Summarizes amalgamated rates for all samples.
stm_summ_lv <- ama_branches_multi_char(stm_list_rates_lv)

# Re-organize data as matrix.
br_rates_mat_lv <- do.call(cbind, stm_summ_lv)
rownames(br_rates_mat_lv) <- paste0("BR_", 1:dim(br_rates_mat_lv)[1])
colnames(br_rates_mat_lv) <- paste0("S_", 1:dim(br_rates_mat_lv)[2])

# Summarizes amalgamated rates across all samples.
stm_summ_lv_mean <- summarize_branch_rates_multi(stm_list_rates_lv, "mean")
stm_summ_lv_mean <- setNames(stm_summ_lv_mean, paste0("BR_", 1:dim(br_rates_mat_lv)[1]))

# Save R object.
#saveRDS(br_rates_mat_lv, file = "data_out/br_rates_larval.RDS")
#saveRDS(stm_summ_lv_mean, file = "data_out/br_rates_larval_ind.RDS")
```

## Save data
```{r}
# Merge final dataset.
br_rates_all <- c(br_rates, list(br_rates_mat_lv))
names(br_rates_all)[16] <- "larval"

br_rates_all_ind <- c(br_rates_ind, list(stm_summ_lv_mean))
names(br_rates_all_ind)[16] <- "larval"

# Save final dataset.
saveRDS(br_rates_all, file = "data_out/br_rates_all.RDS")
saveRDS(br_rates_all_ind, file = "data_out/br_rates_all_ind.RDS")
```
