---
title: "Correlation between pyrate rates and other metrics"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
---



```{r setup, include=F}
library(ape)
library(phytools)
library(ontophylo)
library(dplyr)
library(parallel)
library(viridis)
library(ggplot2)
library(abind)
library(dplyr)
library(purrr)
library(readr)
library(tidyr)
library(stringr)
library(deeptime)
source("R/utils-ST.R")
source('R/region_class.R')


knitr::opts_chunk$set(
  echo = TRUE,       # show code by default
  warning = FALSE,
  message = FALSE
)
```




## Read data

```{r}

# Neff
neff_repl <- read_rds('data_out/neff-per-replicate.RDS')
head(neff_repl)

# Pyrate div
div_sum <- read_rds('data_out/pyrate-dive.RDS')
head(div_sum)

# Disparity
dis_tb <- readRDS("data_out/data_disparity_final.RDS")
# !!! This may not be necessary
# dis_tb <- dis_tb %>%
#   arrange(Time) %>%
#   mutate(Time = rev(Time))
head(dis_tb)

# Rate thru time
rates_thru_time <- readRDS('data_out/rates-thru-time.RDS')
head(rates_thru_time)
```


## Make average Neff

```{r}
# bin edges
bins <- c(265, seq(260, 0, by = -20) )  
length(bins)

# cut times into bins (right=FALSE so [lower,upper) )
neff_repl$bin <- cut(neff_repl$time, breaks=bins, right=FALSE)

# average per bin
avg_neff <- aggregate(mean_entropy ~ bin, data=neff_repl, FUN=mean)
avg_neff
plot(avg_neff)

avg_mean_f_plus <- aggregate(mean_f_plus ~ bin, data=neff_repl, FUN=mean)
avg_mean_f_plus
plot(avg_mean_f_plus)

avg_mean_log_f_plus <- aggregate(mean_log_f_plus ~ bin, data=neff_repl, FUN=mean)
avg_mean_H_plus <- aggregate(mean_H_plus ~ bin, data=neff_repl, FUN=mean)

```

## Make average Disparity

```{r}
# bin edges
bins <- c(265, seq(260, 0, by = -20) )  
length(bins)

# cut times into bins (right=FALSE so [lower,upper) )
dis_tb$bin <- cut(dis_tb$Time, breaks=bins, right=FALSE)

# average per bin
avg_dis <- aggregate(Mean_norm_disparity ~ bin, data=dis_tb, FUN=mean)
avg_dis
plot(avg_dis)
```
## Make average Rate

```{r}
# bin edges
bins <- c(265, seq(260, 0, by = -20) )  
length(bins)

rates_thru_time$bin <- cut(rates_thru_time$time, breaks=bins, right=FALSE)

# average per bin
avg_rate <- aggregate(mean ~ bin, data=rates_thru_time, FUN=mean)
avg_rate
plot(avg_rate)
```


## Pyrate vs. Neff

```{r}

neff_r <- rev(avg_neff[,2])
py_div <- div_sum$mean

plot(neff_r, py_div)

cor.test(neff_r, py_div, method = 'pearson')

cor.test(neff_r[-1], py_div[-1], method = 'pearson')
```


```{r}
plot(neff_r, type = 'l', ylim=c(-0.03, 1.7))
lines(py_div*10, col='red')
```

```{r}
plot(neff_r[-1], type = 'l', ylim=c(-0.03, 1.7))
lines(py_div[-1]*10, col='red')
```


## Pyrate vs. Proportion Enriched

```{r}

f_plus_r <- rev(avg_mean_f_plus[,2])
log_f_plus_r <- rev(avg_mean_log_f_plus[,2])
H_plus_r <- rev(avg_mean_H_plus[,2])

plot(f_plus_r, py_div)

#cor.test(f_plus_r, py_div, method = 'pearson')

cor.test(f_plus_r[-1], py_div[-1], method = 'pearson')
cor.test(log_f_plus_r[-1], py_div[-1], method = 'pearson')
cor.test(H_plus_r[-1], py_div[-1], method = 'pearson')
```



## Pyrate vs. Disp

```{r}

dis_r <- rev(avg_dis[,2])
py_div <- div_sum$mean

plot(dis_r, py_div)

cor.test(dis_r, py_div, method = 'pearson')

cor.test(dis_r[-1], py_div[-1], method = 'pearson')
```

## Pyrate vs. Rate

```{r}

rate_r <- rev(avg_rate[,2])
py_div <- div_sum$mean

plot(rate_r, py_div)

cor.test(rate_r, py_div, method = 'pearson')

cor.test(rate_r[-1], py_div[-1], method = 'pearson')
```
## Rate vs. Dispr

```{r}


plot(rate_r, dis_r)

cor.test(rate_r, dis_r, method = 'pearson')

cor.test(rate_r[-1], dis_r[-1], method = 'pearson')
```
## Rate vs. Dispr

```{r}


plot(rate_r, dis_r)

cor.test(rate_r, dis_r, method = 'pearson')

cor.test(rate_r[-1], dis_r[-1], method = 'pearson')
```


## Rate vs. Neff

```{r}


plot(rate_r, neff_r)

cor.test(rate_r, neff_r, method = 'pearson')

cor.test(rate_r[-1], neff_r[-1], method = 'pearson')
```
```{r}
# neff_repl
# rates_thru_time

plot(rates_thru_time$mean, neff_repl$mean_entropy)
cor.test(rates_thru_time$mean, neff_repl$mean_entropy, method = 'pearson')

```


## Linear regression

```{r}
df <- data.frame(
  py_div = py_div[-1],
  neff_r = neff_r[-1],
  dis_r  = dis_r[-1], 
  rate_r=rate_r[-1],
  f_plus_r=f_plus_r[-1],
  
)

model <- lm(py_div ~ neff_r + dis_r + rate_r, data = df)
summary(model)

model <- lm(py_div ~ neff_r + dis_r + rate_r + f_plus_r, data = df)
summary(model)

```


## Linear regression, contributions

```{r}

# avg_neff <- aggregate(mean_entropy ~ bin, data=neff_repl, FUN=mean)
# avg_neff
# plot(avg_neff)
# 
# avg_mean_f_plus <- aggregate(mean_f_plus ~ bin, data=neff_repl, FUN=mean)
# avg_mean_f_plus
# plot(avg_mean_f_plus)
# 
# avg_mean_log_f_plus <- aggregate(mean_log_f_plus ~ bin, data=neff_repl, FUN=mean)
# avg_mean_H_plus <- aggregate(mean_H_plus ~ bin, data=neff_repl, FUN=mean)



df <- data.frame(
  py_div = py_div[-1],
  neff_r = neff_r[-1],
  f_plus_r=f_plus_r[-1],
  log_f_plus_r = log_f_plus_r[-1],
  H_plus_r = H_plus_r[-1]
  
)

m1 <- lm(py_div ~ log_f_plus_r * H_plus_r, data = df)
summary(m1)

m2 <- lm(py_div ~ f_plus_r * H_plus_r, data = df)
summary(m2)

m2a <- lm(py_div ~ f_plus_r + exp(H_plus_r), data = df)
summary(m2a)

m3 <- lm(py_div ~ log_f_plus_r + H_plus_r, data = df)
summary(m3)

```


# Relative importance analysis

```{r}
library(relaimpo)
calc.relimp(m1, type = "lmg")
```

# Estimates empirical C_f, C_H, C_{cov} values.

```{r}
rel <- calc.relimp(m1, type = "lmg")$lmg
rel / sum(rel)
```

